#pragma config(Motor,  port2,           leftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightFront,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftRear,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightRear,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           goalLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           coneLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           liftRotate,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           clawMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int direction = 0;
int X2 = 0, Y1 = 0, X1 = 0, threshold = 50;

task main()
{
	while (true)
	{
		//Create "deadzone" for Y1/Ch3
		if(abs(vexRT[Ch3]) > threshold)
			Y1 = vexRT[Ch3];
		else
			Y1 = 0;
		//Create "deadzone" for X1/Ch4
		if(abs(vexRT[Ch4]) > threshold)
			X1 = vexRT[Ch4];
		else
			X1 = 0;
		//Create "deadzone" for X2/Ch1
		if(abs(vexRT[Ch1]) > threshold)
			X2 = vexRT[Ch1];
		else
			X2 = 0;

		if (vexRT[Btn8U] == 1)
		{
			direction = 0;
		}
		else if (vexRT[Btn8D] == 1)
		{
			direction = 1;
		}

		if(direction == 1)
		{
			motor[leftFront] = -Y1 + X2 - X1;
			motor[rightFront] = Y1 + X2 - X1;
			motor[leftRear] = -Y1 +  X2 + X1;
			motor[rightRear] = Y1 + X2 + X1;
		}
		else
		{
			motor[leftFront] = Y1 + X2 + X1;
			motor[rightFront] = -Y1 + X2 + X1;
			motor[leftRear] = Y1 +  X2 - X1;
			motor[rightRear] = -Y1 + X2 - X1;
		}
		if (vexRT[Btn5UXmtr2] == 1)
		{
			motor[goalLift] = 127;
		}
		else if (vexRT[Btn5DXmtr2] == 1)
		{
			motor[goalLift] = -127;
		}
		else
		{
			motor[goalLift] = 0;
		}
		if (vexRT[Btn6UXmtr2] == 1)
		{
			motor[coneLift] = 127;
		}
		else if (vexRT[Btn6DXmtr2] == 1)
		{
			motor[coneLift] = -127;
		}
		else
		{
			motor[coneLift] = 0;
		}
		if (vexRT[Btn7RXmtr2] == 1)
		{
			motor[liftRotate] = 127;
		}
		else if (vexRT[Btn7LXmtr2] == 1)
		{
			motor[liftRotate] = -127;
		}
		else
		{
			motor[liftRotate] = 0;
		}
		if (vexRT[Btn8RXmtr2] == 1)
		{
			motor[clawMotor] = 127;
		}
		else if (vexRT[Btn8LXmtr2] == 1)
		{
			motor[clawMotor] = -127;
		}
		else
		{
			motor[clawMotor] = 0;
		}
	}
}
