
#pragma config(Motor,  port2,           leftfront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightfront,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftrear,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightrear,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           goallift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           conelift,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int direction = 0;
int X2 = 0, Y1 = 0, X1 = 0, threshold = 50;

task main()
{
	while (true)
	{
		//Create "deadzone" for Y1/Ch3
		if(abs(vexRT[Ch3]) > threshold)
			Y1 = vexRT[Ch3];
		else
			Y1 = 0;
		//Create "deadzone" for X1/Ch4
		if(abs(vexRT[Ch4]) > threshold)
			X1 = vexRT[Ch4];
		else
			X1 = 0;
		//Create "deadzone" for X2/Ch1
		if(abs(vexRT[Ch1]) > threshold)
			X2 = vexRT[Ch1];
		else
			X2 = 0;

		if (vexRT[Btn8U] == 1)
		{
			direction = 0;
		}
		else if (vexRT[Btn8D] == 1)
		{
			direction = 1;
		}

		else if (vexRT[Btn8L] == 1)
		{
			direction = 2;
		}

		else if (vexRT[Btn8R] == 1)
		{
			direction = 3;
		}

			if(direction == 1)
			{
				motor[leftfront] = -Y1 + X2 - X1;
				motor[rightfront] = Y1 + X2 - X1;
				motor[leftrear] = -Y1 +  X2 + X1;
				motor[rightrear] = Y1 + X2 + X1;
			}
			else
			{
				motor[leftfront] = Y1 + X2 + X1;
				motor[rightfront] = -Y1 + X2 + X1;
				motor[leftrear] = Y1 +  X2 - X1;
				motor[rightrear] = -Y1 + X2 - X1;
			}
			if (vexRT[Btn5U] == 1)
			{
				motor[goallift] = 127;
			}
			else if (vexRT[Btn5D] == 1)
			{
				motor[goallift] = -127;
			}
			else
			{
				motor[goallift] = 0;
				if (vexRT[Btn6U] == 1)
				{
					motor[conelift] = 127;
				}
				else if (vexRT[Btn6D] == 1)
				{
					motor[conelift] = -127;
				}
				else
				{
					motor[conelift] = 0;
				}
			}
		}
	}
