#pragma config(Motor,  port2,           leftfront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightfront,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftrear,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightrear,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		motor[leftfront] = vexRT[Ch3] + vexRT[Ch1] + vexRT[Ch4];
		motor[rightfront] = -vexRT[Ch3] + vexRT[Ch1] + vexRT[Ch4];
		motor[leftrear] = vexRT[Ch3] +  vexRT[Ch1] - vexRT[Ch4];
		motor[rightrear] = -vexRT[Ch3] + vexRT[Ch1] - vexRT[Ch4];
	}
}
